# 보고서용: S2 Parser 결과 통계

In [15]:
# scripts/report_s2_parser_00_stats.py (예시)
import json
from collections import Counter

In [16]:
path = "../runs/s2_parser.ir.jsonl"
n_proto = 0
step_counts = []
qcg_counts = []
data_counts = []
warn_counter = Counter()

In [17]:
with open(path, encoding="utf-8") as f:
    for line in f:
        r = json.loads(line)
        n_proto += 1
        nodes = r["nodes"]
        step_counts.append(sum(1 for n in nodes if n["type"] == "Step"))
        qcg_counts.append(sum(1 for n in nodes if n["type"] == "QCGate"))
        data_counts.append(sum(1 for n in nodes if n["type"] == "DataAnalysis"))
        for w in r.get("warnings", []):
            warn_counter[w.split()[0]] += 1  # prefix 카운트

In [18]:
print("n_protocols:", n_proto)
print("avg_steps:", sum(step_counts) / len(step_counts))
print("avg_qcgates:", sum(qcg_counts) / len(qcg_counts))
print("avg_data_nodes:", sum(data_counts) / len(data_counts))
print("warnings:", warn_counter)

n_protocols: 46
avg_steps: 15.891304347826088
avg_qcgates: 1.1521739130434783
avg_data_nodes: 0.9565217391304348
warnings: Counter({'added_placeholder_step': 366, 'max_nodes': 7})

In [ ]:
# placeholder가 많으면 → Task Miner는 괜찮아도, Methods 내용 자체가 부족하거나, 프롬프트/MAX_NODES 설정이 빡센 것.

# 보고서용: S2B Evidence Only 결과 통계

In [12]:
# scripts/report_s2b_evidence_00_quality.py
import json
from collections import Counter

path = "../runs/s2b_grounded.evidence_only.ir.jsonl"

n_steps = 0
n_with_ev = 0
domain_counter = Counter()
domain_with_ev = Counter()

In [13]:
with open(path, encoding="utf-8") as f:
    for line in f:
        r = json.loads(line)
        domain = r.get("domain") or "unknown"
        nodes = r["nodes"]
        for n in nodes:
            if n.get("type") != "Step":
                continue
            n_steps += 1
            domain_counter[domain] += 1
            if n.get("evidence"):
                n_with_ev += 1
                domain_with_ev[domain] += 1

In [14]:
print("총 Step 수:", n_steps)
print("evidence 있는 Step 수:", n_with_ev, "(비율:", n_with_ev / max(1, n_steps), ")")

print("\n도메인별 coverage:")
for d in sorted(domain_counter.keys()):
    tot = domain_counter[d]
    ok = domain_with_ev[d]
    print(f"  {d:40s}  {ok}/{tot}  ({ok / max(1, tot):.3f})")

총 Step 수: 731
evidence 있는 Step 수: 11 (비율: 0.015047879616963064 )

도메인별 coverage:
  Biochemical & Molecular Functional Analysis  1/64  (0.016)
  Bioimaging Technologies                   1/66  (0.015)
  Cell Biology & Culture                    0/75  (0.000)
  Genomics Technologies                     2/76  (0.026)
  Immunological Techniques                  3/80  (0.037)
  Microbiology & Virology                   3/68  (0.044)
  Model Organism-Specific Techniques        0/60  (0.000)
  Molecular Biology Techniques              0/80  (0.000)
  Neuroscience Methods                      1/82  (0.012)
  Plant Science & Technology                0/80  (0.000)

# 보고서용: IR Evidence Consistency 결과 통계

In [19]:
path = "../eval/ir_evidence_consistency.jsonl"
total = 0
supported = 0

In [20]:
with open(path, encoding="utf-8") as f:
    for line in f:
        r = json.loads(line)
        params = r["params"]
        sup = r["check"]["supported_params"]
        uns = r["check"]["unsupported_params"]
        total += len(params)
        supported += len(sup)

In [21]:

print("총 파라미터 수:", total)
print("지원되는 파라미터 수:", supported)
print("지원 비율:", supported / max(1, total))

총 파라미터 수: 1162
지원되는 파라미터 수: 1138
지원 비율: 0.9793459552495697

In [30]:
path = "../eval/ir_evidence_consistency.no_ev.jsonl"
total = 0
supported = 0

In [31]:
with open(path, encoding="utf-8") as f:
    for line in f:
        r = json.loads(line)
        params = r["params"]
        sup = r["check"]["supported_params"]
        uns = r["check"]["unsupported_params"]
        total += len(params)
        supported += len(sup)

In [32]:

print("총 파라미터 수:", total)
print("지원되는 파라미터 수:", supported)
print("지원 비율:", supported / max(1, total))

총 파라미터 수: 1162
지원되는 파라미터 수: 1141
지원 비율: 0.9819277108433735

# 보고서용: parameter 근거 품질 결과 통계

In [26]:
import json
import pandas as pd

rows = []
with open("../runs/verify_cov_params.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        rows.append(json.loads(line))

df = pd.DataFrame(rows)

# 전체 비율
print(df["verdict"].value_counts(normalize=True))

verdict
supported      0.783333
unsupported    0.128333
ambiguous      0.088333
Name: proportion, dtype: float64

In [28]:
# 프로토콜별 supported 비율
per_proto = df.groupby("protocol_id")["verdict"].value_counts(normalize=True).unstack().fillna(0)
print(per_proto)

verdict            ambiguous  supported  unsupported
protocol_id
Bio-protocol-1010        0.0   1.000000     0.000000
Bio-protocol-1111        0.0   1.000000     0.000000
Bio-protocol-1174        0.0   1.000000     0.000000
Bio-protocol-1213        0.0   0.947368     0.052632
Bio-protocol-1250        0.0   0.894737     0.105263
Bio-protocol-1437        1.0   0.000000     0.000000
Bio-protocol-1537        1.0   0.000000     0.000000
Bio-protocol-1542        0.0   0.937500     0.062500
Bio-protocol-1611        0.0   0.948276     0.051724
Bio-protocol-1716        0.0   0.944444     0.055556
Bio-protocol-1784        0.0   1.000000     0.000000
Bio-protocol-1836        0.0   0.777778     0.222222
Bio-protocol-1861        0.0   0.884615     0.115385
Bio-protocol-2001        0.0   0.818182     0.181818
Bio-protocol-2096        0.0   0.881579     0.118421
Bio-protocol-2219        0.0   0.841270     0.158730
Bio-protocol-2302        0.0   0.809524     0.190476
Bio-protocol-2332        0.0   0.866667     0.133333
Bio-protocol-2350        0.0   0.825000     0.175000
Bio-protocol-2443        1.0   0.000000     0.000000
Bio-protocol-2517        0.0   0.960000     0.040000
Bio-protocol-2519        0.0   0.909091     0.090909
Bio-protocol-2548        0.0   0.934783     0.065217
Bio-protocol-2600        0.0   0.818182     0.181818
Bio-protocol-2602        0.0   0.958333     0.041667
Bio-protocol-2617        0.0   0.941176     0.058824
Bio-protocol-2742        0.0   1.000000     0.000000
Bio-protocol-2974        0.0   0.894737     0.105263
Bio-protocol-3026        0.0   1.000000     0.000000
Bio-protocol-3032        1.0   0.000000     0.000000
Bio-protocol-3144        0.0   0.877193     0.122807
Bio-protocol-3504        0.0   0.916667     0.083333
Bio-protocol-3584        0.0   0.821429     0.178571
Bio-protocol-3607        0.0   1.000000     0.000000
Bio-protocol-3617        0.0   1.000000     0.000000
Bio-protocol-3758        0.0   0.714286     0.285714
Bio-protocol-3816        0.0   0.653846     0.346154
Bio-protocol-3921        1.0   0.000000     0.000000
Bio-protocol-3965        0.0   0.662162     0.337838
Bio-protocol-611         0.0   1.000000     0.000000
Bio-protocol-851         0.0   0.500000     0.500000
Bio-protocol-972         0.0   0.769231     0.230769

In [40]:
pd.set_option('display.max_rows', None)

In [46]:
df[df["protocol_id"] == "Bio-protocol-2096"]

,protocol_id,node_id,param_index,name,value,unit,verdict,evidence_span,llm_raw
0,Bio-protocol-2096,S1,0,Glucose concentration,1.45,%,supported,"Neural stem cells, Cor3–1 were grown in Comple...","{\n ""verdict"": ""supported"",\n ""evidence_..."
1,Bio-protocol-2096,S1,1,penicillin concentration,100.00,units/ml,supported,"Neural stem cells, Cor3–1 were grown in Comple...","{\n ""verdict"": ""supported"",\n ""evidence_..."
2,Bio-protocol-2096,S1,2,streptomycin concentration,100.00,μg/ml,supported,"Neural stem cells, Cor3–1 were grown in Comple...","{\n ""verdict"": ""supported"",\n ""evidence_..."
3,Bio-protocol-2096,S1,3,BSA concentration,0.16,%,supported,"Neural stem cells, Cor3–1 were grown in Comple...","{\n ""verdict"": ""supported"",\n ""evidence_..."
4,Bio-protocol-2096,S1,4,β-Mercapto-ethanol concentration,0.10,mM,supported,"Neural stem cells, Cor3–1 were grown in Comple...","{\n ""verdict"": ""supported"",\n ""evidence_..."
5,Bio-protocol-2096,S1,5,B-27 supplement concentration,1.00,%,supported,"Neural stem cells, Cor3–1 were grown in Comple...","{\n ""verdict"": ""supported"",\n ""evidence_..."
6,Bio-protocol-2096,S1,6,N2 supplement concentration,0.50,%,supported,"Neural stem cells, Cor3–1 were grown in Comple...","{\n ""verdict"": ""supported"",\n ""evidence_..."
7,Bio-protocol-2096,S1,7,mouse EGF concentration,10.00,ng/ml,supported,Before changing the medium or passaging the ce...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
8,Bio-protocol-2096,S1,8,human FGF concentration initial,10.00,ng/ml,supported,Before changing the medium or passaging the ce...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
9,Bio-protocol-2096,S1,9,Laminin concentration,1.00,μg/ml,supported,"Neural stem cells, Cor3–1 were grown in Comple...","{\n ""verdict"": ""supported"",\n ""evidence_..."
10,Bio-protocol-2096,S1,10,priming medium duration,3.00,days,supported,"For neuronal differentiation, 24 hours after s...","{\n ""verdict"": ""supported"",\n ""evidence_..."
11,Bio-protocol-2096,S1,11,differentiation medium duration initial,3.00,days,supported,"For neuronal differentiation, 24 hours after s...","{\n ""verdict"": ""supported"",\n ""evidence_..."
12,Bio-protocol-2096,S1,12,BDNF concentration initial,20.00,ng/ml,supported,Cells were then transferred into a differentia...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
13,Bio-protocol-2096,S1,13,BDNF concentration later,30.00,ng/ml,supported,a constant concentration of BDNF at 30 ng/ml.,"{\n ""verdict"": ""supported"",\n ""evidence_..."
14,Bio-protocol-2096,S2,0,MOI,100.00,None,supported,Transduction of CRE recombinase was performed ...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
15,Bio-protocol-2096,S3,0,FBS concentration,10.00,%,supported,"P19 cells were maintained in MEM-α (Gibco, 410...","{\n ""verdict"": ""supported"",\n ""evidence_..."
16,Bio-protocol-2096,S3,1,penicillin concentration,100.00,units/ml,supported,"Neural stem cells, Cor3–1 were grown in Comple...","{\n ""verdict"": ""supported"",\n ""evidence_..."
17,Bio-protocol-2096,S3,2,streptomycin concentration,100.00,μg/ml,supported,"Neural stem cells, Cor3–1 were grown in Comple...","{\n ""verdict"": ""supported"",\n ""evidence_..."
18,Bio-protocol-2096,S3,3,B-27 supplement concentration,1.00,%,supported,"Neural stem cells, Cor3–1 were grown in Comple...","{\n ""verdict"": ""supported"",\n ""evidence_..."
19,Bio-protocol-2096,S3,4,GlutaMAX concentration,1.00,×,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
20,Bio-protocol-2096,S3,5,Laminin concentration,1.00,μg/ml,supported,"Neural stem cells, Cor3–1 were grown in Comple...","{\n ""verdict"": ""supported"",\n ""evidence_..."
21,Bio-protocol-2096,S4,0,confluence,80.00,%,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
22,Bio-protocol-2096,S4,1,DNA to Lipofectamine ratio,NaN,None,supported,P19 cells were transfected at 80% confluence w...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
23,Bio-protocol-2096,S5,0,thermal cycling initial denaturation temperature,95.00,°C,supported,"Thermal cycling conditions: 95 °C for 5 mins, ...","{\n ""verdict"": ""supported"",\n ""evidence_..."
24,Bio-protocol-2096,S5,1,thermal cycling initial denaturation time,5.00,mins,supported,"Thermal cycling conditions: 95°C for 5 mins, t...","{\n ""verdict"": ""supported"",\n ""evidence_..."
25,Bio-protocol-2096,S5,2,number of cycles,40.00,None,supported,Total RNA was extracted from cells using the R...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
26,Bio-protocol-2096,S5,3,denaturation temperature,95.00,°C,supported,"Thermal cycling conditions: 95 °C for 5 mins, ...","{\n ""verdict"": ""supported"",\n ""evidence_..."
27,Bio-protocol-2096,S5,4,denaturation time,10.00,seconds,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
28,Bio-protocol-2096,S5,5,annealing temperature,60.00,°C,supported,"Thermal cycling conditions: 95°C for 5 mins, t...","{\n ""verdict"": ""supported"",\n ""evidence_..."
29,Bio-protocol-2096,S5,6,annealing time,10.00,seconds,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
30,Bio-protocol-2096,S5,7,extension temperature,72.00,°C,supported,"Thermal cycling conditions: 95°C for 5 mins, t...","{\n ""verdict"": ""supported"",\n ""evidence_..."
31,Bio-protocol-2096,S5,8,extension time,30.00,seconds,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
32,Bio-protocol-2096,S6,0,primary antibody Ascl1 dilution,300.00,fold,supported,Western blots were either performed from total...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
33,Bio-protocol-2096,S6,1,primary antibody Histone H3 dilution,10000.00,fold,supported,"Histone H3 (1:10,000, Abcam, ab1791)","{\n ""verdict"": ""supported"",\n ""evidence_..."
34,Bio-protocol-2096,S6,2,primary antibody α-Tubulin dilution,10000.00,fold,supported,"Histone H3 (1:10,000, Abcam, ab1791) and α-Tub...","{\n ""verdict"": ""supported"",\n ""evidence_..."
35,Bio-protocol-2096,S6,3,primary antibody LaminB dilution,500.00,fold,supported,Western blots were performed from total cell l...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
36,Bio-protocol-2096,S6,4,primary antibody Huwe1 dilution,1000.00,fold,supported,Western blots were performed at least in tripl...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
37,Bio-protocol-2096,S6,5,secondary antibody goat anti-mouse HRP dilution,10000.00,fold,supported,"Mouse secondary (goat anti-mouse HRP 1:10,000,...","{\n ""verdict"": ""supported"",\n ""evidence_..."
38,Bio-protocol-2096,S6,6,secondary antibody rabbit IgG HRP dilution,5000.00,fold,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
39,Bio-protocol-2096,S6,7,blocking time,60.00,mins,supported,Blocking was performed in PBS with 3% BSA for ...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
40,Bio-protocol-2096,S6,8,primary antibody incubation time,NaN,overnight,supported,"Anti-Ascl1 primary antibody (Abcam, ab74065) w...","{\n ""verdict"": ""supported"",\n ""evidence_..."
41,Bio-protocol-2096,S6,9,secondary antibody incubation time,60.00,mins,supported,Blocking was performed in PBS with 3% BSA for ...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
42,Bio-protocol-2096,S7,0,cell seeding Cor3-1,1.50,×10^6 cells,supported,Cor3-1 cells were seeded at 1.5 × 10^6 in 10 c...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
43,Bio-protocol-2096,S7,1,cell seeding P19,1.00,×10^6 cells,supported,P19 cells were seeded at 1.0 × 10^6 in 10 cm d...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
44,Bio-protocol-2096,S7,2,pelleting centrifugation speed initial,1200.00,rpm,supported,"Cells were pelleted at 1,200 rpm in an eppendo...","{\n ""verdict"": ""supported"",\n ""evidence_..."
45,Bio-protocol-2096,S7,3,pelleting centrifugation temperature initial,4.00,°C,supported,"Cells were pelleted at 1,200 rpm in an eppendo...","{\n ""verdict"": ""supported"",\n ""evidence_..."
46,Bio-protocol-2096,S7,4,pelleting centrifugation time initial,3.00,min,supported,"Cells were pelleted at 1,200 rpm in an eppendo...","{\n ""verdict"": ""supported"",\n ""evidence_..."
47,Bio-protocol-2096,S7,5,E1 buffer centrifugation speed,3400.00,rpm,supported,Pellets were covered with 5 volumes of ice-col...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
48,Bio-protocol-2096,S7,6,E1 buffer centrifugation temperature,4.00,°C,supported,"Cells were pelleted at 1,200 rpm in an eppendo...","{\n ""verdict"": ""supported"",\n ""evidence_..."
49,Bio-protocol-2096,S7,7,E1 buffer centrifugation time,2.00,min,supported,Pellets were covered with 5 volumes of ice-col...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
50,Bio-protocol-2096,S7,8,E1 buffer pipetting repetitions,5.00,times,supported,"Cells were pelleted at 1,200 rpm in an eppendo...","{\n ""verdict"": ""supported"",\n ""evidence_..."
51,Bio-protocol-2096,S7,9,E1 buffer ice incubation time,10.00,min,supported,"After centrifugation at 3,400 rpm at 4°C for 2...","{\n ""verdict"": ""supported"",\n ""evidence_..."
52,Bio-protocol-2096,S7,10,E2 buffer centrifugation speed,3400.00,rpm,supported,The solution (chromatin fraction) was sonicate...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
53,Bio-protocol-2096,S7,11,E2 buffer centrifugation temperature,4.00,°C,supported,"After centrifugation at 3,400 rpm at 4 °C for ...","{\n ""verdict"": ""supported"",\n ""evidence_..."
54,Bio-protocol-2096,S7,12,E2 buffer centrifugation time,2.00,min,supported,"After centrifugation at 3,400 rpm at 4°C for 2...","{\n ""verdict"": ""supported"",\n ""evidence_..."
55,Bio-protocol-2096,S7,13,E2 buffer ice incubation time,10.00,min,supported,"After centrifugation at 3,400 rpm at 4°C for 2...","{\n ""verdict"": ""supported"",\n ""evidence_..."
56,Bio-protocol-2096,S7,14,E3 buffer centrifugation speed,3400.00,rpm,supported,"After centrifugation at 3,400 rpm at 4°C for 2...","{\n ""verdict"": ""supported"",\n ""evidence_..."
57,Bio-protocol-2096,S7,15,E3 buffer centrifugation temperature,4.00,°C,supported,"All fractions were centrifuged at 13,000 rpm a...","{\n ""verdict"": ""supported"",\n ""evidence_..."
58,Bio-protocol-2096,S7,16,E3 buffer centrifugation time,2.00,min,supported,"After centrifugation at 3,400 rpm at 4°C for 2...","{\n ""verdict"": ""supported"",\n ""evidence_..."
59,Bio-protocol-2096,S7,17,chromatin sonication time,5.00,min,supported,The solution (chromatin fraction) was sonicate...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
60,Bio-protocol-2096,S7,18,chromatin sonication cycle,NaN,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
61,Bio-protocol-2096,S7,19,chromatin sonication setting,NaN,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
62,Bio-protocol-2096,S7,20,Benzonase dilution,1000.00,fold,supported,The solution (chromatin fraction) was sonicate...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
63,Bio-protocol-2096,S7,21,final centrifugation speed,13000.00,rpm,supported,"All fractions were centrifuged at 13,000 rpm a...","{\n ""verdict"": ""supported"",\n ""evidence_..."
64,Bio-protocol-2096,S7,22,final centrifugation temperature,4.00,°C,supported,"Cells were pelleted at 1,200 rpm in an eppendo...","{\n ""verdict"": ""supported"",\n ""evidence_..."
65,Bio-protocol-2096,S7,23,final centrifugation time,10.00,min,supported,"All fractions were centrifuged at 13,000 rpm a...","{\n ""verdict"": ""supported"",\n ""evidence_..."
66,Bio-protocol-2096,S8,0,Agarose-TUBEs volume,15.00,μl,supported,"15 μl of 50% Agarose-TUBEs (LifeSensors, UM401...","{\n ""verdict"": ""supported"",\n ""evidence_..."
67,Bio-protocol-2096,S8,1,Agarose-TUBEs concentration,50.00,%,supported,"15 μl of 50% Agarose-TUBEs (LifeSensors, UM401...","{\n ""verdict"": ""supported"",\n ""evidence_..."
68,Bio-protocol-2096,S8,2,protein amount range,NaN,μg,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
69,Bio-protocol-2096,S8,3,final volume,500.00,μl,supported,"15 μl of 50% Agarose-TUBEs (LifeSensors, UM401...","{\n ""verdict"": ""supported"",\n ""evidence_..."
70,Bio-protocol-2096,S8,4,incubation time,1.00,hour,supported,Incubation was performed for 1 hour at 4°C on ...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
71,Bio-protocol-2096,S8,5,incubation temperature,4.00,°C,supported,Incubation was performed for 1 hour at 4°C on ...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
72,Bio-protocol-2096,S8,6,centrifugation speed,1000.00,×g,supported,"15 μl of 50% Agarose-TUBEs (LifeSensors, UM401...","{\n ""verdict"": ""supported"",\n ""evidence_..."
73,Bio-protocol-2096,S8,7,centrifugation time,5.00,min,supported,"15 μl of 50% Agarose-TUBEs (LifeSensors, UM401...","{\n ""verdict"": ""supported"",\n ""evidence_..."
74,Bio-protocol-2096,S8,8,boiling time,5.00,min,supported,Agarose-TUBEs were boiled in reducing sample b...,"{\n ""verdict"": ""supported"",\n ""evidence_..."
75,Bio-protocol-2096,S8,9,reducing sample buffer volume,25.00,μl,supported,Agarose-TUBEs were boiled in reducing sample b...,"{\n ""verdict"": ""supported"",\n ""evidence_..."

In [52]:
# 예: unsupported 이면서 evidence_span 이 빈 문자열인 케이스만 모아보기
unsupported = df[(df["unit"] == "×")]
print(unsupported)

           protocol_id node_id  param_index  \
19   Bio-protocol-2096      S3            4
318  Bio-protocol-1437      S8            2
327  Bio-protocol-1437      S8           11
620  Bio-protocol-1611      S6            0
621  Bio-protocol-1611      S6            1

                                       name  value unit      verdict  \
19                   GlutaMAX concentration    1.0    ×  unsupported
318            objective lens magnification   25.0    ×    ambiguous
327                           magnification    2.0    ×    ambiguous
620  beads ratio for large fragment removal    0.2    ×    supported
621  beads ratio for target library binding    0.8    ×    supported

                                         evidence_span  \
19
318
327
620  The PCR reaction was purified with bead-based ...
621  Ampure Xp beads were added to the PCR reaction...

                                               llm_raw
19   {\n    "verdict": "unsupported",\n    "evidenc...
318      {"verdict": "ambiguous", "evidence_span": ""}
327      {"verdict": "ambiguous", "evidence_span": ""}
620  {\n    "verdict": "supported",\n    "evidence_...
621  {\n    "verdict": "supported",\n    "evidence_...

In [ ]:
(df["verdict"] == "unsupported")

In [54]:
import json
import pandas as pd

rows = []
with open("../runs/enhanced_cov_results.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        rows.append(json.loads(line))

df = pd.DataFrame(rows)

# 전체 비율
print(df["verdict"].value_counts(normalize=True))

verdict
supported      0.533333
ambiguous      0.367500
unsupported    0.099167
Name: proportion, dtype: float64

In [55]:
# 프로토콜별 supported 비율
per_proto = df.groupby("protocol_id")["verdict"].value_counts(normalize=True).unstack().fillna(0)
print(per_proto)

verdict            ambiguous  supported  unsupported
protocol_id
Bio-protocol-1010   1.000000   0.000000     0.000000
Bio-protocol-1111   0.000000   1.000000     0.000000
Bio-protocol-1174   1.000000   0.000000     0.000000
Bio-protocol-1213   1.000000   0.000000     0.000000
Bio-protocol-1250   0.000000   0.921053     0.078947
Bio-protocol-1437   0.657143   0.228571     0.114286
Bio-protocol-1537   1.000000   0.000000     0.000000
Bio-protocol-1542   0.000000   0.875000     0.125000
Bio-protocol-1611   0.000000   0.948276     0.051724
Bio-protocol-1716   1.000000   0.000000     0.000000
Bio-protocol-1784   1.000000   0.000000     0.000000
Bio-protocol-1836   0.000000   0.888889     0.111111
Bio-protocol-1861   1.000000   0.000000     0.000000
Bio-protocol-2001   0.818182   0.181818     0.000000
Bio-protocol-2096   0.000000   0.907895     0.092105
Bio-protocol-2219   1.000000   0.000000     0.000000
Bio-protocol-2302   1.000000   0.000000     0.000000
Bio-protocol-2332   1.000000   0.000000     0.000000
Bio-protocol-2350   0.000000   0.800000     0.200000
Bio-protocol-2443   1.000000   0.000000     0.000000
Bio-protocol-2517   0.000000   0.960000     0.040000
Bio-protocol-2519   1.000000   0.000000     0.000000
Bio-protocol-2548   0.739130   0.239130     0.021739
Bio-protocol-2600   1.000000   0.000000     0.000000
Bio-protocol-2602   0.000000   0.875000     0.125000
Bio-protocol-2617   0.000000   0.941176     0.058824
Bio-protocol-2742   0.365854   0.634146     0.000000
Bio-protocol-2974   0.000000   0.868421     0.131579
Bio-protocol-3026   0.000000   1.000000     0.000000
Bio-protocol-3032   1.000000   0.000000     0.000000
Bio-protocol-3144   0.000000   0.859649     0.140351
Bio-protocol-3504   0.000000   0.583333     0.416667
Bio-protocol-3584   0.000000   0.857143     0.142857
Bio-protocol-3607   0.000000   1.000000     0.000000
Bio-protocol-3617   0.000000   1.000000     0.000000
Bio-protocol-3758   0.000000   0.714286     0.285714
Bio-protocol-3816   0.000000   0.666667     0.333333
Bio-protocol-3921   1.000000   0.000000     0.000000
Bio-protocol-3965   0.000000   0.756757     0.243243
Bio-protocol-611    1.000000   0.000000     0.000000
Bio-protocol-851    0.000000   0.500000     0.500000
Bio-protocol-972    0.000000   0.769231     0.230769

In [57]:
# 예: unsupported 이면서 evidence_span 이 빈 문자열인 케이스만 모아보기
unsupported = df[(df["verdict"] == "unsupported")]
unsupported.head(50)

,protocol_id,node_id,param_index,name,value,unit,verdict,evidence_span,llm_raw
19,Bio-protocol-2096,S3,4,GlutaMAX concentration,1.000,×,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
27,Bio-protocol-2096,S5,4,denaturation time,10.000,seconds,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
29,Bio-protocol-2096,S5,6,annealing time,10.000,seconds,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
31,Bio-protocol-2096,S5,8,extension time,30.000,seconds,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
60,Bio-protocol-2096,S7,18,chromatin sonication cycle,NaN,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
61,Bio-protocol-2096,S7,19,chromatin sonication setting,NaN,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
68,Bio-protocol-2096,S8,2,protein amount range,NaN,μg,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
89,Bio-protocol-972,S8,2,rabbit anti-human citrullinated histone H3 ant...,0.010,v/v,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
90,Bio-protocol-972,S8,3,goat anti-human MPO antibody dilution,0.025,v/v,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
91,Bio-protocol-972,S8,4,secondary donkey anti-rabbit IgG Alexa Fluor 5...,0.005,v/v,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
92,Bio-protocol-972,S8,5,secondary donkey anti-goat IgG Alexa Fluor 488...,0.005,v/v,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
93,Bio-protocol-972,S8,6,DAPI dilution,0.001,v/v,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
96,Bio-protocol-972,S8,9,storage time,1.000,day,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
126,Bio-protocol-3144,S4,1,culture age,NaN,days,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
136,Bio-protocol-3144,S6,0,DAB concentration,1.000,mg/ml,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
138,Bio-protocol-3144,S6,2,DAB staining pH,NaN,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
141,Bio-protocol-3144,S6,5,leaf discs incubation time,1.000,hour,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
143,Bio-protocol-3144,S6,7,centrifugation duration,1.000,minute,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
146,Bio-protocol-3144,S7,0,RNA digestion DNase units,1.000,U,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
147,Bio-protocol-3144,S7,1,DNase digestion volume,10.000,μl,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
156,Bio-protocol-3144,S7,10,cDNA volume,2.000,μl,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
177,Bio-protocol-2602,S6,4,Numerical aperture,1.450,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
179,Bio-protocol-2602,D1,1,Smoothing pixel area,NaN,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
180,Bio-protocol-2602,D2,0,Exposure time,5.000,s,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
190,Bio-protocol-1250,S3,1,Confluence for differentiation,NaN,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
199,Bio-protocol-1250,S5,2,Sodium pyruvate concentration,NaN,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
217,Bio-protocol-1250,D2,1,PCR protocol steps,NaN,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
274,Bio-protocol-2617,S7,2,initial serum dilution,1.000,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
282,Bio-protocol-2617,S8,2,initial serum dilution,1.000,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
311,Bio-protocol-1437,S6,0,pore size,0.400,μm,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
318,Bio-protocol-1437,S8,2,objective lens magnification,25.000,×,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
319,Bio-protocol-1437,S8,3,numerical aperture,1.050,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
327,Bio-protocol-1437,S8,11,magnification,2.000,×,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
332,Bio-protocol-3584,S2,3,cluster_method,NaN,None,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
334,Bio-protocol-3584,S2,5,later_iterations_distance_measure,NaN,%,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
350,Bio-protocol-3584,S7,11,primary_antibody_incubation_time,720.000,min,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
353,Bio-protocol-3584,S7,14,secondary_antibody_incubation_time,90.000,min,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
364,Bio-protocol-3965,S3,0,input DNA amount,1.000,μg,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
370,Bio-protocol-3965,S3,6,size fractionation range,NaN,bp,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
371,Bio-protocol-3965,S3,7,elution volume,30.000,μl,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
372,Bio-protocol-3965,S4,0,template volume,20.000,μl,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
384,Bio-protocol-3965,S5,6,Hybridization Component A volume,3.000,μl,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
393,Bio-protocol-3965,S7,1,magnet incubation time,2.000,min,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
403,Bio-protocol-3965,S7,11,Wash Buffer I vortex duration,120.000,sec,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
405,Bio-protocol-3965,S7,13,Wash Buffer II vortex duration,60.000,sec,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
408,Bio-protocol-3965,S7,16,resuspension volume,50.000,μl,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
411,Bio-protocol-3965,S8,2,Illumina adapter concentration,2.000,μM,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
412,Bio-protocol-3965,S8,3,Phusion Master Mix volume,100.000,μl,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
413,Bio-protocol-3965,S8,4,PCR tubes volume per reaction,100.000,μl,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."
415,Bio-protocol-3965,S8,6,initial denaturation time,30.000,sec,unsupported,,"{\n ""verdict"": ""unsupported"",\n ""evidenc..."

In [58]:
import torch

print(torch.backends.mps.is_available())
if torch.backends.mps.is_available():
    x = torch.ones(1, device='mps')
    print(x)

True
tensor([1.], device='mps:0')